/*! 
 * jQuery Steps v1.1.0 - 09/04/2014
 * Copyright (c) 2014 Rafael Staib (http://www.jquery-steps.com)
 * Licensed under MIT http://www.opensource.org/licenses/MIT
 */
(function(f,x){function O(a,b,c){var d=a.children(b.headerTag),e=a.children(b.bodyTag);d.length>e.length?m("One or more corresponding step {0} are missing.","contents"):d.length<e.length&&m("One or more corresponding step {0} are missing.","titles");var g=b.startIndex;c.stepCount=d.length;b.saveState&&f.cookie&&(b=f.cookie("jQu3ry_5teps_St@te_"+p(a)),b=parseInt(b,0),!isNaN(b)&&b<c.stepCount&&(g=b));c.currentIndex=g;d.each(function(b){var c=f(this);b=e.eq(b);var d=b.data("mode"),d=null==d?n.html:v(n,
/^\s*$/.test(d)||isNaN(d)?d:parseInt(d,0)),g=d===n.html||b.data("url")===x?"":b.data("url"),k=d!==n.html&&"1"===b.data("loaded"),c=f.extend({},G,{title:c.html(),content:d===n.html?b.html():"",contentUrl:g,contentMode:d,contentLoaded:k});a.data("steps").push(c)})}function H(a,b){var c=a.find(".steps li").eq(b.currentIndex);a.triggerHandler("finishing",[b.currentIndex])?(c.addClass("done").removeClass("error"),a.triggerHandler("finished",[b.currentIndex])):c.addClass("error")}function y(a){var b=a.data("eventNamespace");
null==b&&(b="."+p(a),a.data("eventNamespace",b));return b}function t(a,b){var c=p(a);return a.find("#"+c+"-t-"+b)}function z(a,b){var c=p(a);return a.find("#"+c+"-p-"+b)}function q(a){return a.data("options")}function k(a){return a.data("state")}function A(a,b){var c=a.data("steps");(0>b||b>=c.length)&&m("Index out of range.");return c[b]}function p(a){var b=a.data("uid");null==b&&(b=a._id(),null==b&&(b="steps-uid-".concat(B),a._id(b)),B++,a.data("uid",b));return b}function v(a,b){I("enumType",a);
I("keyOrValue",b);if("string"===typeof b){var c=a[b];c===x&&m("The enum key '{0}' does not exist.",b);return c}if("number"===typeof b){for(c in a)if(a[c]===b)return b;m("Invalid enum value '{0}'.",b)}else m("Invalid key or value type.")}function P(a,b,c,d){(0>d||d>=c.stepCount)&&m("Index out of range.");if(!(b.forceMoveForward&&d<c.currentIndex)){var e=c.currentIndex;a.triggerHandler("stepChanging",[c.currentIndex,d])?(c.currentIndex=d,C(a,b,c),D(a,b,c,e),w(a,b,c),J(a,b,c),Q(a,b,c,d,e,function(){a.triggerHandler("stepChanged",
[d,e])})):a.find(".steps li").eq(e).addClass("error");return!0}}function R(a){var b=f.extend(!0,{},S,a);return this.each(function(){var a=f(this),d={currentIndex:b.startIndex,currentStep:null,stepCount:0,transitionElement:null};a.data("options",b);a.data("state",d);a.data("steps",[]);O(a,b,d);T(a,b,d);d=y(a);a.bind("canceled"+d,b.onCanceled);a.bind("contentLoaded"+d,b.onContentLoaded);a.bind("finishing"+d,b.onFinishing);a.bind("finished"+d,b.onFinished);a.bind("init"+d,b.onInit);a.bind("stepChanging"+
d,b.onStepChanging);a.bind("stepChanged"+d,b.onStepChanged);b.enableKeyNavigation&&a.bind("keyup"+d,U);a.find(".actions a").bind("click"+d,V);b.autoFocus&&0===B&&t(a,b.startIndex).focus();a.triggerHandler("init",[b.startIndex])})}function K(a,b,c,d,e){(0>d||d>c.stepCount)&&m("Index out of range.");var g=e=f.extend({},G,e);a.data("steps").splice(d,0,g);c.currentIndex!==c.stepCount&&c.currentIndex>=d&&(c.currentIndex++,C(a,b,c));c.stepCount++;var g=a.find(".content"),h=f("<{0}>{1}</{0}>".format(b.headerTag,
e.title)),l=f("<{0}></{0}>".format(b.bodyTag));null!=e.contentMode&&e.contentMode!==n.html||l.html(e.content);0===d?g.prepend(l).prepend(h):z(a,d-1).after(l).after(h);L(a,c,l,d);M(a,b,c,h,d);N(a,b,c,d);d===c.currentIndex&&D(a,b,c);w(a,b,c);return a}function U(a){var b=f(this),c=q(b),d=k(b);if(c.suppressPaginationOnFocus&&b.find(":focus").is(":input"))return a.preventDefault(),!1;37===a.keyCode?(a.preventDefault(),u(b,c,d,d.currentIndex-1)):39===a.keyCode&&(a.preventDefault(),u(b,c,d,d.currentIndex+
1))}function J(a,b,c){if(0<c.stepCount){var d=c.currentIndex,e=A(a,d);if(!b.enableContentCache||!e.contentLoaded)switch(v(n,e.contentMode)){case n.iframe:a.find(".content > .body").eq(c.currentIndex).empty().html('<iframe src="'+e.contentUrl+'" frameborder="0" scrolling="no" />').data("loaded","1");break;case n.async:var g=z(a,d)._aria("busy","true").empty().append(E(b.loadingTemplate,{text:b.labels.loading}));f.ajax({url:e.contentUrl,cache:!1}).done(function(b){g.empty().html(b)._aria("busy","false").data("loaded",
"1");a.triggerHandler("contentLoaded",[d])})}}}function u(a,b,c,d){var e=c.currentIndex;return 0<=d&&d<c.stepCount&&!(b.forceMoveForward&&d<c.currentIndex)?(a=t(a,d),b=a.parent(),d=b.hasClass("disabled"),b._enableAria(),a.click(),e===c.currentIndex&&d?(b._enableAria(!1),!1):!0):!1}function V(a){a.preventDefault();var b=f(this);a=b.parent().parent().parent().parent();var c=q(a),d=k(a),b=b.attr("href");switch(b.substring(b.lastIndexOf("#")+1)){case "cancel":a.triggerHandler("canceled");break;case "finish":H(a,
d);break;case "next":u(a,c,d,d.currentIndex+1);break;case "previous":u(a,c,d,d.currentIndex-1)}}function w(a,b,c){if(b.enablePagination){var d=a.find(".actions a[href$='#finish']").parent(),e=a.find(".actions a[href$='#next']").parent();b.forceMoveForward||a.find(".actions a[href$='#previous']").parent()._enableAria(0<c.currentIndex);b.enableFinishButton&&b.showFinishButtonAlways?(d._enableAria(0<c.stepCount),e._enableAria(1<c.stepCount&&c.stepCount>c.currentIndex+1)):(d._showAria(b.enableFinishButton&&
c.stepCount===c.currentIndex+1),e._showAria(0===c.stepCount||c.stepCount>c.currentIndex+1)._enableAria(c.stepCount>c.currentIndex+1||!b.enableFinishButton))}}function D(a,b,c,d){var e=t(a,c.currentIndex),g=f('<span class="current-info audible">'+b.labels.current+" </span>");b=a.find(".content > .title");null!=d&&(a=t(a,d),a.parent().addClass("done").removeClass("error")._selectAria(!1),b.eq(d).removeClass("current").next(".body").removeClass("current"),g=a.find(".current-info"),e.focus());e.prepend(g).parent()._selectAria().removeClass("done")._enableAria();
b.eq(c.currentIndex).addClass("current").next(".body").addClass("current")}function N(a,b,c,d){for(var e=p(a);d<c.stepCount;d++){var f=e+"-t-"+d,h=e+"-p-"+d,l=e+"-h-"+d,k=a.find(".title").eq(d)._id(l);a.find(".steps a").eq(d)._id(f)._aria("controls",h).attr("href","#"+l).html(E(b.titleTemplate,{index:d+1,title:k.html()}));a.find(".body").eq(d)._id(h)._aria("labelledby",l)}}function T(a,b,c){var d=v(F,b.stepsOrientation)===F.vertical?" vertical":"",e=f('<{0} class="{1}">{2}</{0}>'.format(b.contentContainerTag,
"content "+b.clearFixCssClass,a.html())),g=f('<{0} class="{1}">{2}</{0}>'.format(b.stepsContainerTag,"steps "+b.clearFixCssClass,'<ul role="tablist"></ul>')),h=e.children(b.headerTag),l=e.children(b.bodyTag);a.attr("role","application").empty().append(g).append(e).addClass(b.cssClass+" "+b.clearFixCssClass+d);l.each(function(b){L(a,c,f(this),b)});h.each(function(d){M(a,b,c,f(this),d)});D(a,b,c);W(a,b,c)}function L(a,b,c,d){a=p(a);var e=a+"-h-"+d;c._id(a+"-p-"+d).attr("role","tabpanel")._aria("labelledby",
e).addClass("body")._showAria(b.currentIndex===d)}function W(a,b,c){if(b.enablePagination){var d="";b.forceMoveForward||(d+='<li><a href="#{0}" role="menuitem">{1}</a></li>'.format("previous",b.labels.previous));d+='<li><a href="#{0}" role="menuitem">{1}</a></li>'.format("next",b.labels.next);b.enableFinishButton&&(d+='<li><a href="#{0}" role="menuitem">{1}</a></li>'.format("finish",b.labels.finish));b.enableCancelButton&&(d+='<li><a href="#{0}" role="menuitem">{1}</a></li>'.format("cancel",b.labels.cancel));
a.append('<{0} class="actions {1}"><ul role="menu" aria-label="{2}">{3}</ul></{0}>'.format(b.actionContainerTag,b.clearFixCssClass,b.labels.pagination,d));w(a,b,c);J(a,b,c)}}function E(a,b){for(var c=a.match(/#([a-z]*)#/gi),d=0;d<c.length;d++){var e=c[d],f=e.substring(1,e.length-1);b[f]===x&&m("The key '{0}' does not exist in the substitute collection!",f);a=a.replace(e,b[f])}return a}function M(a,b,c,d,e){var g=p(a),h=g+"-t-"+e,l=g+"-p-"+e,g=g+"-h-"+e,k=a.find(".steps > ul"),m=E(b.titleTemplate,
{index:e+1,title:d.html()}),h=f('<li role="tab"><a id="'+h+'" href="#'+g+'" aria-controls="'+l+'">'+m+"</a></li>");h._enableAria(b.enableAllSteps||c.currentIndex>e);c.currentIndex>e&&h.addClass("done");d._id(g).attr("tabindex","-1").addClass("title");0===e?k.prepend(h):k.find("li").eq(e-1).after(h);0===e&&k.find("li").removeClass("first").eq(e).addClass("first");e===c.stepCount-1&&k.find("li").removeClass("last").eq(e).addClass("last");h.children("a").bind("click"+y(a),X)}function C(a,b,c){b.saveState&&
f.cookie&&f.cookie("jQu3ry_5teps_St@te_"+p(a),c.currentIndex)}function Q(a,b,c,d,e,g){var h=a.find(".content > .body");a=v(r,b.transitionEffect);var l=b.transitionEffectSpeed;b=h.eq(d);h=h.eq(e);switch(a){case r.fade:case r.slide:d=a===r.fade?"fadeOut":"slideUp";var m=a===r.fade?"fadeIn":"slideDown";c.transitionElement=b;h[d](l,function(){var a=f(this)._showAria(!1).parent().parent(),a=k(a);a.transitionElement&&(a.transitionElement[m](l,function(){f(this)._showAria()}).promise().done(g),a.transitionElement=
null)});break;case r.slideLeft:c=h.outerWidth(!0);a=d>e?c:-c;f.when(h.animate({left:d>e?-c:c},l,function(){f(this)._showAria(!1)}),b.css("left",a+"px")._showAria().animate({left:0},l)).done(g);break;default:f.when(h._showAria(!1),b._showAria()).done(g)}}function X(a){a.preventDefault();var b=f(this);a=b.parent().parent().parent().parent();var c=q(a),d=k(a),e=d.currentIndex;b.parent().is(":not(.disabled):not(.current)")&&(b=b.attr("href"),b=parseInt(b.substring(b.lastIndexOf("-")+1),0),P(a,c,d,b));
if(e===d.currentIndex)return t(a,e).focus(),!1}function m(a){1<arguments.length&&(a=a.format(Array.prototype.slice.call(arguments,1)));throw Error(a);}function I(a,b){null==b&&m("The argument '{0}' is null or undefined.",a)}f.fn.extend({_aria:function(a,b){return this.attr("aria-"+a,b)},_removeAria:function(a){return this.removeAttr("aria-"+a)},_enableAria:function(a){return null==a||a?this.removeClass("disabled")._aria("disabled","false"):this.addClass("disabled")._aria("disabled","true")},_showAria:function(a){return null==
a||a?this.show()._aria("hidden","false"):this.hide()._aria("hidden","true")},_selectAria:function(a){return null==a||a?this.addClass("current")._aria("selected","true"):this.removeClass("current")._aria("selected","false")},_id:function(a){return a?this.attr("id",a):this.attr("id")}});String.prototype.format||(String.prototype.format=function(){for(var a=1===arguments.length&&f.isArray(arguments[0])?arguments[0]:arguments,b=this,c=0;c<a.length;c++)b=b.replace(new RegExp("\\{"+c+"\\}","gm"),a[c]);
return b});var B=0;f.fn.steps=function(a){if(f.fn.steps[a])return f.fn.steps[a].apply(this,Array.prototype.slice.call(arguments,1));if("object"!==typeof a&&a)f.error("Method "+a+" does not exist on jQuery.steps");else return R.apply(this,arguments)};f.fn.steps.add=function(a){var b=k(this);return K(this,q(this),b,b.stepCount,a)};f.fn.steps.destroy=function(){var a=q(this),b=y(this);this.unbind(b).removeData("uid").removeData("options").removeData("state").removeData("steps").removeData("eventNamespace").find(".actions a").unbind(b);
this.removeClass(a.clearFixCssClass+" vertical");a=this.find(".content > *");a.removeData("loaded").removeData("mode").removeData("url");a.removeAttr("id").removeAttr("role").removeAttr("tabindex").removeAttr("class").removeAttr("style")._removeAria("labelledby")._removeAria("hidden");this.find(".content > [data-mode='async'],.content > [data-mode='iframe']").empty();a=f('<{0} class="{1}"></{0}>'.format(this.get(0).tagName,this.attr("class")));b=this._id();null!=b&&""!==b&&a._id(b);a.html(this.find(".content").html());
this.after(a);this.remove();return a};f.fn.steps.finish=function(){H(this,k(this))};f.fn.steps.getCurrentIndex=function(){return k(this).currentIndex};f.fn.steps.getCurrentStep=function(){return A(this,k(this).currentIndex)};f.fn.steps.getStep=function(a){return A(this,a)};f.fn.steps.insert=function(a,b){return K(this,q(this),k(this),a,b)};f.fn.steps.next=function(){var a=q(this),b=k(this);return u(this,a,b,b.currentIndex+1)};f.fn.steps.previous=function(){var a=q(this),b=k(this);return u(this,a,
b,b.currentIndex-1)};f.fn.steps.remove=function(a){var b=q(this),c=k(this);if(0>a||a>=c.stepCount||c.currentIndex===a)a=!1;else{this.data("steps").splice(a,1);c.currentIndex>a&&(c.currentIndex--,C(this,b,c));c.stepCount--;var d=p(this);this.find("#"+d+"-h-"+a).remove();z(this,a).remove();t(this,a).parent().remove();0===a&&this.find(".steps li").first().addClass("first");a===c.stepCount&&this.find(".steps li").eq(a).addClass("last");N(this,b,c,a);w(this,b,c);a=!0}return a};f.fn.steps.setStep=function(a,
b){throw Error("Not yet implemented!");};f.fn.steps.skip=function(a){throw Error("Not yet implemented!");};var n=f.fn.steps.contentMode={html:0,iframe:1,async:2},F=f.fn.steps.stepsOrientation={horizontal:0,vertical:1},r=f.fn.steps.transitionEffect={none:0,fade:1,slide:2,slideLeft:3},G=f.fn.steps.stepModel={title:"",content:"",contentUrl:"",contentMode:n.html,contentLoaded:!1},S=f.fn.steps.defaults={headerTag:"h1",bodyTag:"div",contentContainerTag:"div",actionContainerTag:"div",stepsContainerTag:"div",
cssClass:"wizard",clearFixCssClass:"clearfix",stepsOrientation:F.horizontal,titleTemplate:'<span class="number">#index#.</span> #title#',loadingTemplate:'<span class="spinner"></span> #text#',autoFocus:!1,enableAllSteps:!1,enableKeyNavigation:!0,enablePagination:!0,suppressPaginationOnFocus:!0,enableContentCache:!0,enableCancelButton:!1,enableFinishButton:!0,preloadContent:!1,showFinishButtonAlways:!1,forceMoveForward:!1,saveState:!1,startIndex:0,transitionEffect:r.none,transitionEffectSpeed:200,
onStepChanging:function(a,b,c){return!0},onStepChanged:function(a,b,c){},onCanceled:function(a){},onFinishing:function(a,b){return!0},onFinished:function(a,b){},onContentLoaded:function(a,b){},onInit:function(a,b){},labels:{cancel:"Cancel",current:"current step:",pagination:"Pagination",finish:"Finish",next:"Next",previous:"Previous",loading:"Loading ..."}}})(jQuery);