/*!
 * jQuery Cycle Plugin (with Transition Definitions)
 * Examples and documentation at: http://jquery.malsup.com/cycle/
 * Copyright (c) 2007-2010 M. Alsup
 * Version: 2.9998 (27-OCT-2011)
 * Dual licensed under the MIT and GPL licenses.
 * http://jquery.malsup.com/license.html
 * Requires: jQuery v1.3.2 or later
 */
(function(e,c){function h(b){e.fn.cycle.debug&&a(b)}function a(){window.console&&console.log&&console.log("[cycle] "+Array.prototype.join.call(arguments," "))}function l(b,g,a){var d=e(b).data("cycle.opts"),c=!!b.cyclePause;c&&d.paused?d.paused(b,d,g,a):!c&&d.resumed&&d.resumed(b,d,g,a)}function k(b,g,m){function d(b,g,m){if(!b&&!0===g){b=e(m).data("cycle.opts");if(!b)return a("options not found, can not resume"),!1;m.cycleTimeout&&(clearTimeout(m.cycleTimeout),m.cycleTimeout=0);x(b.elements,b,1,
!b.backwards)}}b.cycleStop==c&&(b.cycleStop=0);if(g===c||null===g)g={};if(g.constructor==String)switch(g){case "destroy":case "stop":m=e(b).data("cycle.opts");if(!m)return!1;b.cycleStop++;b.cycleTimeout&&clearTimeout(b.cycleTimeout);b.cycleTimeout=0;m.elements&&e(m.elements).stop();e(b).removeData("cycle.opts");"destroy"==g&&n(m);return!1;case "toggle":return b.cyclePause=1===b.cyclePause?0:1,d(b.cyclePause,m,b),l(b),!1;case "pause":return b.cyclePause=1,l(b),!1;case "resume":return b.cyclePause=
0,d(!1,m,b),l(b),!1;case "prev":case "next":m=e(b).data("cycle.opts");if(!m)return a('options not found, "prev/next" ignored'),!1;e.fn.cycle[g](m);return!1;default:g={fx:g}}else if(g.constructor==Number){var k=g;g=e(b).data("cycle.opts");if(!g)return a("options not found, can not advance slide"),!1;if(0>k||k>=g.elements.length)return a("invalid slide index: "+k),!1;g.nextSlide=k;b.cycleTimeout&&(clearTimeout(b.cycleTimeout),b.cycleTimeout=0);"string"==typeof m&&(g.oneTimeFx=m);x(g.elements,g,1,k>=
g.currSlide);return!1}return g}function d(b,g){if(!e.support.opacity&&g.cleartype&&b.style.filter)try{b.style.removeAttribute("filter")}catch(a){}}function n(b){b.next&&e(b.next).unbind(b.prevNextEvent);b.prev&&e(b.prev).unbind(b.prevNextEvent);(b.pager||b.pagerAnchorBuilder)&&e.each(b.pagerAnchors||[],function(){this.unbind().remove()});b.pagerAnchors=null;b.destroy&&b.destroy(b)}function r(b,g,m,k,D){var u,f=e.extend({},e.fn.cycle.defaults,k||{},e.metadata?b.metadata():e.meta?b.data():{}),h=e.isFunction(b.data)?
b.data(f.metaAttr):null;h&&(f=e.extend(f,h));f.autostop&&(f.countdown=f.autostopCount||m.length);var n=b[0];b.data("cycle.opts",f);f.$cont=b;f.stopCount=n.cycleStop;f.elements=m;f.before=f.before?[f.before]:[];f.after=f.after?[f.after]:[];!e.support.opacity&&f.cleartype&&f.after.push(function(){d(this,f)});f.continuous&&f.after.push(function(){x(m,f,0,!f.backwards)});q(f);e.support.opacity||!f.cleartype||f.cleartypeNoBg||v(g);"static"==b.css("position")&&b.css("position","relative");f.width&&b.width(f.width);
f.height&&"auto"!=f.height&&b.height(f.height);f.startingSlide!=c?(f.startingSlide=parseInt(f.startingSlide,10),f.startingSlide>=m.length||0>f.startSlide?f.startingSlide=0:u=!0):f.startingSlide=f.backwards?m.length-1:0;if(f.random){f.randomMap=[];for(h=0;h<m.length;h++)f.randomMap.push(h);f.randomMap.sort(function(b,g){return Math.random()-.5});if(u)for(u=0;u<m.length;u++)f.startingSlide==f.randomMap[u]&&(f.randomIndex=u);else f.randomIndex=1,f.startingSlide=f.randomMap[1]}else f.startingSlide>=m.length&&
(f.startingSlide=0);f.currSlide=f.startingSlide||0;var t=f.startingSlide;g.css({position:"absolute",top:0,left:0}).hide().each(function(b){b=f.backwards?t?b<=t?m.length+(b-t):t-b:m.length-b:t?b>=t?m.length-(b-t):t-b:m.length-b;e(this).css("z-index",b)});e(m[t]).css("opacity",1).show();d(m[t],f);f.fit&&(f.aspect?g.each(function(){var b=e(this),g=!0===f.aspect?b.width()/b.height():f.aspect;f.width&&b.width()!=f.width&&(b.width(f.width),b.height(f.width/g));f.height&&b.height()<f.height&&(b.height(f.height),
b.width(f.height*g))}):(f.width&&g.width(f.width),f.height&&"auto"!=f.height&&g.height(f.height)));!f.center||f.fit&&!f.aspect||g.each(function(){var b=e(this);b.css({"margin-left":f.width?(f.width-b.width())/2+"px":0,"margin-top":f.height?(f.height-b.height())/2+"px":0})});!f.center||f.fit||f.slideResize||g.each(function(){var b=e(this);b.css({"margin-left":f.width?(f.width-b.width())/2+"px":0,"margin-top":f.height?(f.height-b.height())/2+"px":0})});if(f.containerResize&&!b.innerHeight()){for(var r=
h=u=0;r<m.length;r++){var z=e(m[r]),A=z[0],y=z.outerWidth(),B=z.outerHeight();y||(y=A.offsetWidth||A.width||z.attr("width"));B||(B=A.offsetHeight||A.height||z.attr("height"));u=y>u?y:u;h=B>h?B:h}0<u&&0<h&&b.css({width:u+"px",height:h+"px"})}var F=!1;f.pause&&b.hover(function(){F=!0;this.cyclePause++;l(n,!0)},function(){F&&this.cyclePause--;l(n,!0)});if(!1===w(f))return!1;var G=!1;k.requeueAttempts=k.requeueAttempts||0;g.each(function(){var b=e(this);this.cycleH=f.fit&&f.height?f.height:b.height()||
this.offsetHeight||this.height||b.attr("height")||0;this.cycleW=f.fit&&f.width?f.width:b.width()||this.offsetWidth||this.width||b.attr("width")||0;if(b.is("img")){var b=e.browser.mozilla&&34==this.cycleW&&19==this.cycleH&&!this.complete,g=e.browser.opera&&(42==this.cycleW&&19==this.cycleH||37==this.cycleW&&17==this.cycleH)&&!this.complete,m=0==this.cycleH&&0==this.cycleW&&!this.complete;if(e.browser.msie&&28==this.cycleW&&30==this.cycleH&&!this.complete||b||g||m){if(D.s&&f.requeueOnImageNotLoaded&&
100>++k.requeueAttempts)return a(k.requeueAttempts," - img slide not loaded, requeuing slideshow: ",this.src,this.cycleW,this.cycleH),setTimeout(function(){e(D.s,D.c).cycle(k)},f.requeueTimeout),G=!0,!1;a("could not determine size of image: "+this.src,this.cycleW,this.cycleH)}}return!0});if(G)return!1;f.cssBefore=f.cssBefore||{};f.cssAfter=f.cssAfter||{};f.cssFirst=f.cssFirst||{};f.animIn=f.animIn||{};f.animOut=f.animOut||{};g.not(":eq("+t+")").css(f.cssBefore);e(g[t]).css(f.cssFirst);if(f.timeout)for(f.timeout=
parseInt(f.timeout,10),f.speed.constructor==String&&(f.speed=e.fx.speeds[f.speed]||parseInt(f.speed,10)),f.sync||(f.speed/=2),u="none"==f.fx?0:"shuffle"==f.fx?500:250;f.timeout-f.speed<u;)f.timeout+=f.speed;f.easing&&(f.easeIn=f.easeOut=f.easing);f.speedIn||(f.speedIn=f.speed);f.speedOut||(f.speedOut=f.speed);f.slideCount=m.length;f.currSlide=f.lastSlide=t;f.random?(++f.randomIndex==m.length&&(f.randomIndex=0),f.nextSlide=f.randomMap[f.randomIndex]):f.nextSlide=f.backwards?0==f.startingSlide?m.length-
1:f.startingSlide-1:f.startingSlide>=m.length-1?0:f.startingSlide+1;if(!f.multiFx)if(u=e.fn.cycle.transitions[f.fx],e.isFunction(u))u(b,g,f);else if("custom"!=f.fx&&!f.multiFx)return a("unknown transition: "+f.fx,"; slideshow terminating"),!1;b=g[t];f.skipInitializationCallbacks||(f.before.length&&f.before[0].apply(b,[b,b,f,!0]),f.after.length&&f.after[0].apply(b,[b,b,f,!0]));f.next&&e(f.next).bind(f.prevNextEvent,function(){return C(f,1)});f.prev&&e(f.prev).bind(f.prevNextEvent,function(){return C(f,
0)});(f.pager||f.pagerAnchorBuilder)&&E(m,f);H(f,m);return f}function q(b){b.original={before:[],after:[]};b.original.cssBefore=e.extend({},b.cssBefore);b.original.cssAfter=e.extend({},b.cssAfter);b.original.animIn=e.extend({},b.animIn);b.original.animOut=e.extend({},b.animOut);e.each(b.before,function(){b.original.before.push(this)});e.each(b.after,function(){b.original.after.push(this)})}function w(b){var g,m,d=e.fn.cycle.transitions;if(0<b.fx.indexOf(",")){b.multiFx=!0;b.fxs=b.fx.replace(/\s*/g,
"").split(",");for(g=0;g<b.fxs.length;g++){var k=b.fxs[g];m=d[k];m&&d.hasOwnProperty(k)&&e.isFunction(m)||(a("discarding unknown transition: ",k),b.fxs.splice(g,1),g--)}if(!b.fxs.length)return a("No valid transitions named; slideshow terminating."),!1}else if("all"==b.fx)for(p in b.multiFx=!0,b.fxs=[],d)m=d[p],d.hasOwnProperty(p)&&e.isFunction(m)&&b.fxs.push(p);if(b.multiFx&&b.randomizeEffects){m=Math.floor(20*Math.random())+30;for(g=0;g<m;g++)d=Math.floor(Math.random()*b.fxs.length),b.fxs.push(b.fxs.splice(d,
1)[0]);h("randomized fx sequence: ",b.fxs)}return!0}function H(b,g){b.addSlide=function(a,d){var k=e(a),c=k[0];b.autostopCount||b.countdown++;g[d?"unshift":"push"](c);if(b.els)b.els[d?"unshift":"push"](c);b.slideCount=g.length;b.random&&(b.randomMap.push(b.slideCount-1),b.randomMap.sort(function(b,g){return Math.random()-.5}));k.css("position","absolute");k[d?"prependTo":"appendTo"](b.$cont);d&&(b.currSlide++,b.nextSlide++);e.support.opacity||!b.cleartype||b.cleartypeNoBg||v(k);b.fit&&b.width&&k.width(b.width);
b.fit&&b.height&&"auto"!=b.height&&k.height(b.height);c.cycleH=b.fit&&b.height?b.height:k.height();c.cycleW=b.fit&&b.width?b.width:k.width();k.css(b.cssBefore);(b.pager||b.pagerAnchorBuilder)&&e.fn.cycle.createPagerAnchor(g.length-1,c,e(b.pager),g,b);if(e.isFunction(b.onAddSlide))b.onAddSlide(k);else k.hide()}}function x(b,g,a,d){function k(){var a=0;g.timeout&&!g.continuous?(a=y(b[g.currSlide],b[g.nextSlide],g,d),"shuffle"==g.fx&&(a-=g.speedOut)):g.continuous&&l.cyclePause&&(a=10);0<a&&(l.cycleTimeout=
setTimeout(function(){x(b,g,0,!g.backwards)},a))}a&&g.busy&&g.manualTrump&&(h("manualTrump in go(), stopping active transition"),e(b).stop(!0,!0),g.busy=0);if(g.busy)h("transition active, ignoring new tx request");else{var l=g.$cont[0],f=b[g.currSlide],n=b[g.nextSlide];if(l.cycleStop==g.stopCount&&(0!==l.cycleTimeout||a))if(a||l.cyclePause||g.bounce||!(g.autostop&&0>=--g.countdown||g.nowrap&&!g.random&&g.nextSlide<g.currSlide)){var r=!1;if(!a&&l.cyclePause||g.nextSlide==g.currSlide)k();else{var r=
!0,t=g.fx;f.cycleH=f.cycleH||e(f).height();f.cycleW=f.cycleW||e(f).width();n.cycleH=n.cycleH||e(n).height();n.cycleW=n.cycleW||e(n).width();g.multiFx&&(d&&(g.lastFx==c||++g.lastFx>=g.fxs.length)?g.lastFx=0:!d&&(g.lastFx==c||0>--g.lastFx)&&(g.lastFx=g.fxs.length-1),t=g.fxs[g.lastFx]);g.oneTimeFx&&(t=g.oneTimeFx,g.oneTimeFx=null);e.fn.cycle.resetState(g,t);g.before.length&&e.each(g.before,function(b,a){l.cycleStop==g.stopCount&&a.apply(n,[f,n,g,d])});var q=function(){g.busy=0;e.each(g.after,function(b,
a){l.cycleStop==g.stopCount&&a.apply(n,[f,n,g,d])});l.cycleStop||k()};h("tx firing("+t+"); currSlide: "+g.currSlide+"; nextSlide: "+g.nextSlide);g.busy=1;if(g.fxFn)g.fxFn(f,n,g,q,d,a&&g.fastOnEvent);else if(e.isFunction(e.fn.cycle[g.fx]))e.fn.cycle[g.fx](f,n,g,q,d,a&&g.fastOnEvent);else e.fn.cycle.custom(f,n,g,q,d,a&&g.fastOnEvent)}if(r||g.nextSlide==g.currSlide)g.lastSlide=g.currSlide,g.random?(g.currSlide=g.nextSlide,++g.randomIndex==b.length&&(g.randomIndex=0,g.randomMap.sort(function(b,a){return Math.random()-
.5})),g.nextSlide=g.randomMap[g.randomIndex],g.nextSlide==g.currSlide&&(g.nextSlide=g.currSlide==g.slideCount-1?0:g.currSlide+1)):g.backwards?(a=0>g.nextSlide-1)&&g.bounce?(g.backwards=!g.backwards,g.nextSlide=1,g.currSlide=0):(g.nextSlide=a?b.length-1:g.nextSlide-1,g.currSlide=a?0:g.nextSlide+1):(a=g.nextSlide+1==b.length)&&g.bounce?(g.backwards=!g.backwards,g.nextSlide=b.length-2,g.currSlide=b.length-1):(g.nextSlide=a?0:g.nextSlide+1,g.currSlide=a?b.length-1:g.nextSlide-1);r&&g.pager&&g.updateActivePagerLink(g.pager,
g.currSlide,g.activePagerClass)}else g.end&&g.end(g)}}function y(b,a,e,d){if(e.timeoutFn){for(b=e.timeoutFn.call(b,b,a,e,d);"none"!=e.fx&&250>b-e.speed;)b+=e.speed;h("calculated timeout: "+b+"; speed: "+e.speed);if(!1!==b)return b}return e.timeout}function C(b,a){var d=a?1:-1,k=b.elements,c=b.$cont[0],l=c.cycleTimeout;l&&(clearTimeout(l),c.cycleTimeout=0);if(b.random&&0>d)b.randomIndex--,-2==--b.randomIndex?b.randomIndex=k.length-2:-1==b.randomIndex&&(b.randomIndex=k.length-1),b.nextSlide=b.randomMap[b.randomIndex];
else if(b.random)b.nextSlide=b.randomMap[b.randomIndex];else if(b.nextSlide=b.currSlide+d,0>b.nextSlide){if(b.nowrap)return!1;b.nextSlide=k.length-1}else if(b.nextSlide>=k.length){if(b.nowrap)return!1;b.nextSlide=0}c=b.onPrevNextEvent||b.prevNextClick;e.isFunction(c)&&c(0<d,b.nextSlide,k[b.nextSlide]);x(k,b,1,a);return!1}function E(b,a){var d=e(a.pager);e.each(b,function(k,c){e.fn.cycle.createPagerAnchor(k,c,d,b,a)});a.updateActivePagerLink(a.pager,a.startingSlide,a.activePagerClass)}function v(b){function a(b){b=
parseInt(b,10).toString(16);return 2>b.length?"0"+b:b}function d(b){for(;b&&"html"!=b.nodeName.toLowerCase();b=b.parentNode){var k=e.css(b,"background-color");if(k&&0<=k.indexOf("rgb"))return b=k.match(/\d+/g),"#"+a(b[0])+a(b[1])+a(b[2]);if(k&&"transparent"!=k)return k}return"#ffffff"}h("applying clearType background-color hack");b.each(function(){e(this).css("background-color",d(this))})}e.support==c&&(e.support={opacity:!e.browser.msie});e.expr[":"].paused=function(b){return b.cyclePause};e.fn.cycle=
function(b,g){var d={s:this.selector,c:this.context};if(0===this.length&&"stop"!=b){if(!e.isReady&&d.s)return a("DOM not ready, queuing slideshow"),e(function(){e(d.s,d.c).cycle(b,g)}),this;a("terminating; zero elements found by selector"+(e.isReady?"":" (DOM not ready)"));return this}return this.each(function(){var c=k(this,b,g);if(!1!==c){c.updateActivePagerLink=c.updateActivePagerLink||e.fn.cycle.updateActivePagerLink;this.cycleTimeout&&clearTimeout(this.cycleTimeout);this.cycleTimeout=this.cyclePause=
0;var l=e(this),n=c.slideExpr?e(c.slideExpr,this):l.children(),f=n.get(),q=r(l,n,f,c,d);if(!1!==q)if(2>f.length)a("terminating; too few slides: "+f.length);else if(l=q.continuous?10:y(f[q.currSlide],f[q.nextSlide],q,!q.backwards))l+=q.delay||0,10>l&&(l=10),h("first timeout: "+l),this.cycleTimeout=setTimeout(function(){x(f,q,0,!c.backwards)},l)}})};e.fn.cycle.resetState=function(b,a){a=a||b.fx;b.before=[];b.after=[];b.cssBefore=e.extend({},b.original.cssBefore);b.cssAfter=e.extend({},b.original.cssAfter);
b.animIn=e.extend({},b.original.animIn);b.animOut=e.extend({},b.original.animOut);b.fxFn=null;e.each(b.original.before,function(){b.before.push(this)});e.each(b.original.after,function(){b.after.push(this)});var d=e.fn.cycle.transitions[a];e.isFunction(d)&&d(b.$cont,e(b.elements),b)};e.fn.cycle.updateActivePagerLink=function(b,a,d){e(b).each(function(){e(this).children().removeClass(d).eq(a).addClass(d)})};e.fn.cycle.next=function(b){C(b,1)};e.fn.cycle.prev=function(b){C(b,0)};e.fn.cycle.createPagerAnchor=
function(b,a,d,k,c){e.isFunction(c.pagerAnchorBuilder)?(a=c.pagerAnchorBuilder(b,a),h("pagerAnchorBuilder("+b+", el) returned: "+a)):a='<a href="#">'+(b+1)+"</a>";if(a){var n=e(a);if(0===n.parents("body").length){var f=[];1<d.length?(d.each(function(){var b=n.clone(!0);e(this).append(b);f.push(b[0])}),n=e(f)):n.appendTo(d)}c.pagerAnchors=c.pagerAnchors||[];c.pagerAnchors.push(n);d=function(a){a.preventDefault();c.nextSlide=b;a=c.$cont[0];var f=a.cycleTimeout;f&&(clearTimeout(f),a.cycleTimeout=0);
a=c.onPagerEvent||c.pagerClick;e.isFunction(a)&&a(c.nextSlide,k[c.nextSlide]);x(k,c,1,c.currSlide<b)};/mouseenter|mouseover/i.test(c.pagerEvent)?n.hover(d,function(){}):n.bind(c.pagerEvent,d);/^click/.test(c.pagerEvent)||c.allowPagerClickBubble||n.bind("click.cycle",function(){return!1});var q=c.$cont[0],r=!1;c.pauseOnPagerHover&&n.hover(function(){r=!0;q.cyclePause++;l(q,!0,!0)},function(){r&&q.cyclePause--;l(q,!0,!0)})}};e.fn.cycle.hopsFromLast=function(b,a){var e=b.lastSlide,d=b.currSlide;return a?
d>e?d-e:b.slideCount-e:d<e?e-d:e+b.slideCount-d};e.fn.cycle.commonReset=function(b,a,d,c,k,l){e(d.elements).not(b).hide();"undefined"==typeof d.cssBefore.opacity&&(d.cssBefore.opacity=1);d.cssBefore.display="block";d.slideResize&&!1!==c&&0<a.cycleW&&(d.cssBefore.width=a.cycleW);d.slideResize&&!1!==k&&0<a.cycleH&&(d.cssBefore.height=a.cycleH);d.cssAfter=d.cssAfter||{};d.cssAfter.display="none";e(b).css("zIndex",d.slideCount+(!0===l?1:0));e(a).css("zIndex",d.slideCount+(!0===l?0:1))};e.fn.cycle.custom=
function(b,a,d,c,k,l){var f=e(b),h=e(a),n=d.speedIn;b=d.speedOut;var q=d.easeIn;a=d.easeOut;h.css(d.cssBefore);l&&(n="number"==typeof l?b=l:b=1,q=a=null);var r=function(){h.animate(d.animIn,n,q,function(){c()})};f.animate(d.animOut,b,a,function(){f.css(d.cssAfter);d.sync||r()});d.sync&&r()};e.fn.cycle.transitions={fade:function(b,a,d){a.not(":eq("+d.currSlide+")").css("opacity",0);d.before.push(function(b,a,d){e.fn.cycle.commonReset(b,a,d);d.cssBefore.opacity=0});d.animIn={opacity:1};d.animOut={opacity:0};
d.cssBefore={top:0,left:0}}};e.fn.cycle.ver=function(){return"2.9998"};e.fn.cycle.defaults={activePagerClass:"activeSlide",after:null,allowPagerClickBubble:!1,animIn:null,animOut:null,aspect:!1,autostop:0,autostopCount:0,backwards:!1,before:null,center:null,cleartype:!e.support.opacity,cleartypeNoBg:!1,containerResize:1,continuous:0,cssAfter:null,cssBefore:null,delay:0,easeIn:null,easeOut:null,easing:null,end:null,fastOnEvent:0,fit:0,fx:"fade",fxFn:null,height:"auto",manualTrump:!0,metaAttr:"cycle",
next:null,nowrap:0,onPagerEvent:null,onPrevNextEvent:null,pager:null,pagerAnchorBuilder:null,pagerEvent:"click.cycle",pause:0,pauseOnPagerHover:0,prev:null,prevNextEvent:"click.cycle",random:0,randomizeEffects:1,requeueOnImageNotLoaded:!0,requeueTimeout:250,rev:0,shuffle:null,skipInitializationCallbacks:!1,slideExpr:null,slideResize:1,speed:1E3,speedIn:null,speedOut:null,startingSlide:0,sync:1,timeout:4E3,timeoutFn:null,updateActivePagerLink:null,width:null}})(jQuery);
(function(e){e.fn.cycle.transitions.none=function(c,h,a){a.fxFn=function(a,c,d,h){e(c).show();e(a).hide();h()}};e.fn.cycle.transitions.fadeout=function(c,h,a){h.not(":eq("+a.currSlide+")").css({display:"block",opacity:1});a.before.push(function(a,c,d,h,r,q){e(a).css("zIndex",d.slideCount+(!0===!q?1:0));e(c).css("zIndex",d.slideCount+(!0===!q?0:1))});a.animIn.opacity=1;a.animOut.opacity=0;a.cssBefore.opacity=1;a.cssBefore.display="block";a.cssAfter.zIndex=0};e.fn.cycle.transitions.scrollUp=function(c,
h,a){c.css("overflow","hidden");a.before.push(e.fn.cycle.commonReset);c=c.height();a.cssBefore.top=c;a.cssBefore.left=0;a.cssFirst.top=0;a.animIn.top=0;a.animOut.top=-c};e.fn.cycle.transitions.scrollDown=function(c,h,a){c.css("overflow","hidden");a.before.push(e.fn.cycle.commonReset);c=c.height();a.cssFirst.top=0;a.cssBefore.top=-c;a.cssBefore.left=0;a.animIn.top=0;a.animOut.top=c};e.fn.cycle.transitions.scrollLeft=function(c,h,a){c.css("overflow","hidden");a.before.push(e.fn.cycle.commonReset);c=
c.width();a.cssFirst.left=0;a.cssBefore.left=c;a.cssBefore.top=0;a.animIn.left=0;a.animOut.left=0-c};e.fn.cycle.transitions.scrollRight=function(c,h,a){c.css("overflow","hidden");a.before.push(e.fn.cycle.commonReset);c=c.width();a.cssFirst.left=0;a.cssBefore.left=-c;a.cssBefore.top=0;a.animIn.left=0;a.animOut.left=c};e.fn.cycle.transitions.scrollHorz=function(c,h,a){c.css("overflow","hidden").width();a.before.push(function(a,c,d,h){d.rev&&(h=!h);e.fn.cycle.commonReset(a,c,d);d.cssBefore.left=h?c.cycleW-
1:1-c.cycleW;d.animOut.left=h?-a.cycleW:a.cycleW});a.cssFirst.left=0;a.cssBefore.top=0;a.animIn.left=0;a.animOut.top=0};e.fn.cycle.transitions.scrollVert=function(c,h,a){c.css("overflow","hidden");a.before.push(function(a,c,d,h){d.rev&&(h=!h);e.fn.cycle.commonReset(a,c,d);d.cssBefore.top=h?1-c.cycleH:c.cycleH-1;d.animOut.top=h?a.cycleH:-a.cycleH});a.cssFirst.top=0;a.cssBefore.left=0;a.animIn.top=0;a.animOut.left=0};e.fn.cycle.transitions.slideX=function(c,h,a){a.before.push(function(a,c,d){e(d.elements).not(a).hide();
e.fn.cycle.commonReset(a,c,d,!1,!0);d.animIn.width=c.cycleW});a.cssBefore.left=0;a.cssBefore.top=0;a.cssBefore.width=0;a.animIn.width="show";a.animOut.width=0};e.fn.cycle.transitions.slideY=function(c,h,a){a.before.push(function(a,c,d){e(d.elements).not(a).hide();e.fn.cycle.commonReset(a,c,d,!0,!1);d.animIn.height=c.cycleH});a.cssBefore.left=0;a.cssBefore.top=0;a.cssBefore.height=0;a.animIn.height="show";a.animOut.height=0};e.fn.cycle.transitions.shuffle=function(c,h,a){c=c.css("overflow","visible").width();
h.css({left:0,top:0});a.before.push(function(a,c,d){e.fn.cycle.commonReset(a,c,d,!0,!0,!0)});a.speedAdjusted||(a.speed/=2,a.speedAdjusted=!0);a.random=0;a.shuffle=a.shuffle||{left:-c,top:15};a.els=[];for(c=0;c<h.length;c++)a.els.push(h[c]);for(c=0;c<a.currSlide;c++)a.els.push(a.els.shift());a.fxFn=function(a,c,d,h,r){d.rev&&(r=!r);var q=r?e(a):e(c);e(c).css(d.cssBefore);var w=d.slideCount;q.animate(d.shuffle,d.speedIn,d.easeIn,function(){for(var c=e.fn.cycle.hopsFromLast(d,r),k=0;k<c;k++)r?d.els.push(d.els.shift()):
d.els.unshift(d.els.pop());if(r)for(c=0,k=d.els.length;c<k;c++)e(d.els[c]).css("z-index",k-c+w);else c=e(a).css("z-index"),q.css("z-index",parseInt(c,10)+1+w);q.animate({left:0,top:0},d.speedOut,d.easeOut,function(){e(r?this:a).hide();h&&h()})})};e.extend(a.cssBefore,{display:"block",opacity:1,top:0,left:0})};e.fn.cycle.transitions.turnUp=function(c,h,a){a.before.push(function(a,c,d){e.fn.cycle.commonReset(a,c,d,!0,!1);d.cssBefore.top=c.cycleH;d.animIn.height=c.cycleH;d.animOut.width=c.cycleW});a.cssFirst.top=
0;a.cssBefore.left=0;a.cssBefore.height=0;a.animIn.top=0;a.animOut.height=0};e.fn.cycle.transitions.turnDown=function(c,h,a){a.before.push(function(a,c,d){e.fn.cycle.commonReset(a,c,d,!0,!1);d.animIn.height=c.cycleH;d.animOut.top=a.cycleH});a.cssFirst.top=0;a.cssBefore.left=0;a.cssBefore.top=0;a.cssBefore.height=0;a.animOut.height=0};e.fn.cycle.transitions.turnLeft=function(c,h,a){a.before.push(function(a,c,d){e.fn.cycle.commonReset(a,c,d,!1,!0);d.cssBefore.left=c.cycleW;d.animIn.width=c.cycleW});
a.cssBefore.top=0;a.cssBefore.width=0;a.animIn.left=0;a.animOut.width=0};e.fn.cycle.transitions.turnRight=function(c,h,a){a.before.push(function(a,c,d){e.fn.cycle.commonReset(a,c,d,!1,!0);d.animIn.width=c.cycleW;d.animOut.left=a.cycleW});e.extend(a.cssBefore,{top:0,left:0,width:0});a.animIn.left=0;a.animOut.width=0};e.fn.cycle.transitions.zoom=function(c,h,a){a.before.push(function(a,c,d){e.fn.cycle.commonReset(a,c,d,!1,!1,!0);d.cssBefore.top=c.cycleH/2;d.cssBefore.left=c.cycleW/2;e.extend(d.animIn,
{top:0,left:0,width:c.cycleW,height:c.cycleH});e.extend(d.animOut,{width:0,height:0,top:a.cycleH/2,left:a.cycleW/2})});a.cssFirst.top=0;a.cssFirst.left=0;a.cssBefore.width=0;a.cssBefore.height=0};e.fn.cycle.transitions.fadeZoom=function(c,h,a){a.before.push(function(a,c,d){e.fn.cycle.commonReset(a,c,d,!1,!1);d.cssBefore.left=c.cycleW/2;d.cssBefore.top=c.cycleH/2;e.extend(d.animIn,{top:0,left:0,width:c.cycleW,height:c.cycleH})});a.cssBefore.width=0;a.cssBefore.height=0;a.animOut.opacity=0};e.fn.cycle.transitions.blindX=
function(c,h,a){c=c.css("overflow","hidden").width();a.before.push(function(a,c,d){e.fn.cycle.commonReset(a,c,d);d.animIn.width=c.cycleW;d.animOut.left=a.cycleW});a.cssBefore.left=c;a.cssBefore.top=0;a.animIn.left=0;a.animOut.left=c};e.fn.cycle.transitions.blindY=function(c,h,a){c=c.css("overflow","hidden").height();a.before.push(function(a,c,d){e.fn.cycle.commonReset(a,c,d);d.animIn.height=c.cycleH;d.animOut.top=a.cycleH});a.cssBefore.top=c;a.cssBefore.left=0;a.animIn.top=0;a.animOut.top=c};e.fn.cycle.transitions.blindZ=
function(c,h,a){h=c.css("overflow","hidden").height();c=c.width();a.before.push(function(a,c,d){e.fn.cycle.commonReset(a,c,d);d.animIn.height=c.cycleH;d.animOut.top=a.cycleH});a.cssBefore.top=h;a.cssBefore.left=c;a.animIn.top=0;a.animIn.left=0;a.animOut.top=h;a.animOut.left=c};e.fn.cycle.transitions.growX=function(c,h,a){a.before.push(function(a,c,d){e.fn.cycle.commonReset(a,c,d,!1,!0);d.cssBefore.left=this.cycleW/2;d.animIn.left=0;d.animIn.width=this.cycleW;d.animOut.left=0});a.cssBefore.top=0;a.cssBefore.width=
0};e.fn.cycle.transitions.growY=function(c,h,a){a.before.push(function(a,c,d){e.fn.cycle.commonReset(a,c,d,!0,!1);d.cssBefore.top=this.cycleH/2;d.animIn.top=0;d.animIn.height=this.cycleH;d.animOut.top=0});a.cssBefore.height=0;a.cssBefore.left=0};e.fn.cycle.transitions.curtainX=function(c,h,a){a.before.push(function(a,c,d){e.fn.cycle.commonReset(a,c,d,!1,!0,!0);d.cssBefore.left=c.cycleW/2;d.animIn.left=0;d.animIn.width=this.cycleW;d.animOut.left=a.cycleW/2;d.animOut.width=0});a.cssBefore.top=0;a.cssBefore.width=
0};e.fn.cycle.transitions.curtainY=function(c,h,a){a.before.push(function(a,c,d){e.fn.cycle.commonReset(a,c,d,!0,!1,!0);d.cssBefore.top=c.cycleH/2;d.animIn.top=0;d.animIn.height=c.cycleH;d.animOut.top=a.cycleH/2;d.animOut.height=0});a.cssBefore.height=0;a.cssBefore.left=0};e.fn.cycle.transitions.cover=function(c,h,a){var l=a.direction||"left",k=c.css("overflow","hidden").width(),d=c.height();a.before.push(function(a,c,h){e.fn.cycle.commonReset(a,c,h);"right"==l?h.cssBefore.left=-k:"up"==l?h.cssBefore.top=
d:"down"==l?h.cssBefore.top=-d:h.cssBefore.left=k});a.animIn.left=0;a.animIn.top=0;a.cssBefore.top=0;a.cssBefore.left=0};e.fn.cycle.transitions.uncover=function(c,h,a){var l=a.direction||"left",k=c.css("overflow","hidden").width(),d=c.height();a.before.push(function(a,c,h){e.fn.cycle.commonReset(a,c,h,!0,!0,!0);"right"==l?h.animOut.left=k:"up"==l?h.animOut.top=-d:"down"==l?h.animOut.top=d:h.animOut.left=-k});a.animIn.left=0;a.animIn.top=0;a.cssBefore.top=0;a.cssBefore.left=0};e.fn.cycle.transitions.toss=
function(c,h,a){var l=c.css("overflow","visible").width(),k=c.height();a.before.push(function(a,c,h){e.fn.cycle.commonReset(a,c,h,!0,!0,!0);h.animOut.left||h.animOut.top?h.animOut.opacity=0:e.extend(h.animOut,{left:2*l,top:-k/2,opacity:0})});a.cssBefore.left=0;a.cssBefore.top=0;a.animIn.left=0};e.fn.cycle.transitions.wipe=function(c,h,a){var l=c.css("overflow","hidden").width(),k=c.height();a.cssBefore=a.cssBefore||{};var d;a.clip&&(/l2r/.test(a.clip)?d="rect(0px 0px "+k+"px 0px)":/r2l/.test(a.clip)?
d="rect(0px "+l+"px "+k+"px "+l+"px)":/t2b/.test(a.clip)?d="rect(0px "+l+"px 0px 0px)":/b2t/.test(a.clip)?d="rect("+k+"px "+l+"px "+k+"px 0px)":/zoom/.test(a.clip)&&(c=parseInt(k/2,10),h=parseInt(l/2,10),d="rect("+c+"px "+h+"px "+c+"px "+h+"px)"));a.cssBefore.clip=a.cssBefore.clip||d||"rect(0px 0px 0px 0px)";c=a.cssBefore.clip.match(/(\d+)/g);var n=parseInt(c[0],10),r=parseInt(c[1],10),q=parseInt(c[2],10),w=parseInt(c[3],10);a.before.push(function(a,c,d){if(a!=c){var h=e(a),E=e(c);e.fn.cycle.commonReset(a,
c,d,!0,!0,!1);d.cssAfter.display="block";var v=1,b=parseInt(d.speedIn/13,10)-1;(function m(){var a=n?n-parseInt(n/b*v,10):0,c=w?w-parseInt(w/b*v,10):0,d=q<k?q+parseInt(v*((k-q)/b||1),10):k,e=r<l?r+parseInt(v*((l-r)/b||1),10):l;E.css({clip:"rect("+a+"px "+e+"px "+d+"px "+c+"px)"});v++<=b?setTimeout(m,13):h.css("display","none")})()}});e.extend(a.cssBefore,{display:"block",opacity:1,top:0,left:0});a.animIn={left:0};a.animOut={left:0}}})(jQuery);