var window_height=$(window).height(),testMobile,loadingError='<p class="error">The Content cannot be loaded.</p>',current,next,prev,target,hash,url,page,title,projectIndex,scrollPostition,projectLength,ajaxLoading=!1,wrapperHeight,pageRefresh=!0,content=!1,loader=$("div#loader"),portfolioGrid=$("div#portfolio-wrap"),projectContainer=$("div#ajax-content-inner"),projectNav=$("#project-navigation ul"),exitProject=$("div#closeProject a"),easing="easeOutExpo",folderName="portfolio";
function initializePortfolio(){function c(){loader.fadeIn().removeClass("projectError").html("");ajaxLoading||(ajaxLoading=!0,projectContainer.load(url+" div#ajaxpage",function(a,b,c){"success"==b&&(ajaxLoading=!1,page=$("div#ajaxpage"),$(".flexslider").flexslider({animation:"fade",slideDirection:"horizontal",slideshow:!0,slideshowSpeed:3500,animationDuration:500,directionNav:!0,controlNav:!0}),jQuery("#ajaxpage").waitForImages(function(){d()}),$(".container").fitVids());"error"==b&&(loader.addClass("projectError").append(loadingError),
loader.find("p").slideDown())}))}function d(){loader.fadeOut("fast",function(){f()})}function f(){0==content?(wrapperHeight=projectContainer.children("div#ajaxpage").outerHeight()+"px",projectContainer.animate({opacity:1,height:wrapperHeight},function(){$(".container").fitVids();scrollPostition=$("html,body").scrollTop();projectNav.fadeIn();exitProject.fadeIn();content=!0})):(wrapperHeight=projectContainer.children("div#ajaxpage").outerHeight()+"px",projectContainer.animate({opacity:1,height:wrapperHeight},
function(){$(".container").fitVids();scrollPostition=$("html,body").scrollTop();projectNav.fadeIn();exitProject.fadeIn()}));projectIndex=portfolioGrid.find("div.portfolio-item.current").index();projectLength=$("div.portfolio-item .portfolio").length-1;projectIndex==projectLength?($("ul li#nextProject a").addClass("disabled"),$("ul li#prevProject a").removeClass("disabled")):0==projectIndex?($("ul li#prevProject a").addClass("disabled"),$("ul li#nextProject a").removeClass("disabled")):$("ul li#nextProject a,ul li#prevProject a").removeClass("disabled")}
function e(a){projectNav.fadeOut(100);exitProject.fadeOut(100);projectContainer.animate({opacity:0,height:"0px"});projectContainer.empty();portfolioGrid.find("div.portfolio-item.current").children().removeClass("active");portfolioGrid.find("div.portfolio-item.current").removeClass("current")}$(window).bind("hashchange",function(){hash=$(window.location).attr("hash");var a="#!"+folderName+"/",b=a.length;if(hash.substr(0,b)==a){var d=$("nav").outerHeight()+50;hash=$(window.location).attr("hash");url=
hash.replace(/[#\!]/g,"");portfolioGrid.find("div.portfolio-item.current").children().removeClass("active");portfolioGrid.find("div.portfolio-item.current").removeClass("current");if(1==pageRefresh&&hash.substr(0,b)==a)$("html,body").stop().animate({scrollTop:projectContainer.offset().top-20+"px"},800,"easeOutExpo",function(){c()});else if(0==pageRefresh&&hash.substr(0,b)==a)$("html,body").stop().animate({scrollTop:projectContainer.offset().top-d+"px"},800,"easeOutExpo",function(){0==content?c():
projectContainer.animate({opacity:0,height:wrapperHeight},function(){c()});projectNav.fadeOut("100");exitProject.fadeOut("100")});else if(""==hash&&0==pageRefresh||hash.substr(0,b)!=a&&0==pageRefresh||hash.substr(0,b)!=a&&1==pageRefresh)scrollPostition=hash,$("html,body").stop().animate({scrollTop:scrollPostition+"px"},1E3,function(){e()});portfolioGrid.find('div.portfolio-item .portfolio a[href="#!'+url+'"]').parent().parent().addClass("current");portfolioGrid.find("div.portfolio-item.current").find(".portfolio").addClass("active")}});
$("#nextProject a").on("click",function(){current=portfolioGrid.find(".portfolio-item.current");next=current.next(".portfolio-item");target=$(next).children("div").children("a").attr("href");$(this).attr("href",target);if(0===next.length)return!1;current.removeClass("current");current.children().removeClass("active");next.addClass("current");next.children().addClass("active")});$("#prevProject a").on("click",function(){current=portfolioGrid.find(".portfolio-item.current");prev=current.prev(".portfolio-item");
target=$(prev).children("div").children("a").attr("href");$(this).attr("href",target);if(0===prev.length)return!1;current.removeClass("current");current.children().removeClass("active");prev.addClass("current");prev.children().addClass("active")});$("#closeProject a").on("click",function(){e($(this).attr("href"));portfolioGrid.find("div.portfolio-item.current").children().removeClass("active");loader.fadeOut();$("html, body").delay(1E3).animate({scrollTop:$(".portfolio-top").offset().top-120},800);
return!1});pageRefresh=!1}$(document).ready(function(){initializePortfolio()});$(window).load(function(){$("#load").fadeOut().remove();$(window).trigger("hashchange");$(window).trigger("resize");$('[data-spy="scroll"]').each(function(){$(this).scrollspy("refresh")})});