/*!
 * skrollr core
 *
 * Alexander Prinzhorn - https://github.com/Prinzhorn/skrollr
 *
 * Free to use under terms of MIT license
 */
(function(g,D,E){var R,S,T,U,V;function u(a){c=D.documentElement;v=D.body;xa();n=this;a=a||{};da=a.constants||{};if(a.easing)for(var b in a.easing)M[b]=a.easing[b];ea=a.edgeStrategy||"set";F={beforerender:a.beforerender,render:a.render};(N=!1!==a.forceHeight)&&(fa=a.scale||1);W=a.mobileDeceleration||ya;ga=!1!==a.smoothScrolling;X=a.smoothScrollingDuration||za;R=n.getScrollTop();V=U=T=S=void 0;(B=(a.mobileCheck||function(){return/Android|iPhone|iPad|iPod|BlackBerry|Windows Phone/i.test(navigator.userAgent||
navigator.vendor||g.opera)})())?((G=D.getElementById("skrollr-body"))&&Aa(),Ba(),H(c,[L,Ca],[ha])):H(c,[L,Da],[ha]);n.refresh();ia(g,"resize orientationchange",function(){var a=c.clientWidth,b=c.clientHeight;if(b!==ja||a!==ka)ja=b,ka=a,Y=!0});var h=Ea();(function d(){Y&&(Y=!1,la());var a=n.getScrollTop(),b,q=J();l?(q>=l.endTime?(a=l.targetTop,b=l.done,l=E):(a=l.easing((q-l.startTime)/l.duration),a=l.startTop+a*l.topDiff|0),n.setScrollTop(a,!0)):B||(R-a&&(S=I,T=a-I,R=a,U=Z,V=Z+X),q<=V&&(a=M.sqrt((q-
U)/X),a=S+a*T|0));B&&G&&K.setStyle(G,"transform","translate(0, "+-O+"px) "+P);if(Q||I!==a){ma=a>=I?"down":"up";Q=!1;var na={curTop:a,lastTop:I,maxTop:x,direction:ma};if(!1!==(F.beforerender&&F.beforerender.call(n,na))){for(var Fa=a,w=n.getScrollTop(),e=0,Ga=z.length;e<Ga;e++){var p=z[e],g=p.element,f=p.smoothScrolling?Fa:w,c=p.keyFrames,t=f<c[0].frame,m=f>c[c.length-1].frame,u=c[t?0:c.length-1],A;if(t||m){if(t&&-1===p.edge||m&&1===p.edge)continue;H(g,[t?"skrollable-before":"skrollable-after"],["skrollable-before",
"skrollable-between","skrollable-after"]);p.edge=t?-1:1;switch(p.edgeStrategy){case "reset":aa(g);continue;case "ease":f=u.frame;break;default:case "set":f=u.props;for(A in f)ba.call(f,A)&&(t=oa(f[A].value),K.setStyle(g,A,t));continue}}else 0!==p.edge&&(H(g,["skrollable","skrollable-between"],["skrollable-before","skrollable-after"]),p.edge=0);t=0;for(p=c.length-1;t<p;t++)if(f>=c[t].frame&&f<=c[t+1].frame){p=c[t];c=c[t+1];for(A in p.props)if(ba.call(p.props,A)){var u=(f-p.frame)/(c.frame-p.frame),
u=p.props[A].easing(u),t=p.props[A].value,m=c.props[A].value,v=void 0,C=t.length;if(C!==m.length)throw"Can't interpolate between \""+t[0]+'" and "'+m[0]+'"';for(var D=[t[0]],v=1;v<C;v++)D[v]=t[v]+(m[v]-t[v])*u;t=D;t=oa(t);K.setStyle(g,A,t)}break}}I=a;F.render&&F.render.call(n,na)}b&&b.call(n,!1)}Z=q;h(d)})();return n}var K=g.skrollr={get:function(){return n},init:function(a){return n||new u(a)},VERSION:"0.6.11"},ba=Object.prototype.hasOwnProperty,f=g.Math,ca=g.getComputedStyle,c,v,L="skrollr",ha=
"no-"+L,Da=L+"-desktop",Ca=L+"-mobile",ya=.004,za=200,pa=/^\s+|\s+$/g,Ha=/^data(?:-(_\w+))?(?:-?(-?\d+))?(?:-?(start|end|top|center|bottom))?(?:-?(top|center|bottom))?$/,Ia=/\s*([\w\-\[\]]+)\s*:\s*(.+?)\s*(?:;|$)/gi,Ja=/^([a-z\-]+)\[(\w+)\]$/,Ka=/-([a-z])/g,La=function(a,b){return b.toUpperCase()},qa=/[\-+]?[\d]*\.?[\d]+/g,ra=/\{\?\}/g,sa=/rgba?\(\s*-?\d+\s*,\s*-?\d+\s*,\s*-?\d+/g,ta=/[a-z\-]+-gradient/g,m="",C="",xa=function(){var a=/^(?:O|Moz|webkit|ms)|(?:-(?:o|moz|webkit|ms)-)/;if(ca){var b=ca(v,
null),h;for(h in b)if(m=h.match(a)||+h==h&&b[h].match(a))break;m?(m=m[0],"-"===m.slice(0,1)?(C=m,m={"-webkit-":"webkit","-moz-":"Moz","-ms-":"ms","-o-":"O"}[m]):C="-"+m.toLowerCase()+"-"):m=C=""}},Ea=function(){var a=g.requestAnimationFrame||g[m.toLowerCase()+"RequestAnimationFrame"],b=J();if(B||!a)a=function(a){var r=J()-b,r=f.max(0,1E3/60-r);g.setTimeout(function(){b=J();a()},r)};return a},M={begin:function(){return 0},end:function(){return 1},linear:function(a){return a},quadratic:function(a){return a*
a},cubic:function(a){return a*a*a},swing:function(a){return-f.cos(a*f.PI)/2+.5},sqrt:function(a){return f.sqrt(a)},outCubic:function(a){return f.pow(a-1,3)+1},bounce:function(a){var b;if(.5083>=a)b=3;else if(.8489>=a)b=9;else if(.96208>=a)b=27;else if(.99981>=a)b=91;else return 1;return 1-f.abs(3*f.cos(a*b*1.028)/b)}};u.prototype.refresh=function(a){var b,h,r=!1;a===E?(r=!0,z=[],ua=0,a=D.getElementsByTagName("*")):a=[].concat(a);b=0;for(h=a.length;b<h;b++){var d=a[b],k=d,y=[],q=ga,c=ea;if(d.attributes){for(var f=
0,w=d.attributes.length;f<w;f++){var e=d.attributes[f];if("data-anchor-target"===e.name){if(k=D.querySelector(e.value),null===k)throw'Unable to find anchor target "'+e.value+'"';}else if("data-smooth-scrolling"===e.name)q="off"!==e.value;else if("data-edge-strategy"===e.name)c=e.value;else{var g=e.name.match(Ha);if(null!==g){var p=g[1],p=p&&da[p.substr(1)]||0,p=(g[2]|0)+p,l=g[3],g=g[4]||l,e={offset:p,props:e.value,element:d};y.push(e);l&&"start"!==l&&"end"!==l?(e.mode="relative",e.anchors=[l,g]):
(e.mode="absolute","end"===l?e.isEnd=!0:(e.frame=p*fa,delete e.offset))}}}y.length&&(!r&&"___skrollable_id"in d?(e=d.___skrollable_id,f=z[e].styleAttr,w=z[e].classAttr):(e=d.___skrollable_id=ua++,f=d.style.cssText,w=va(d)),z[e]={element:d,styleAttr:f,classAttr:w,anchorTarget:k,keyFrames:y,smoothScrolling:q,edgeStrategy:c},H(d,["skrollable"],[]))}}la();b=0;for(h=a.length;b<h;b++)if(r=z[a[b].___skrollable_id],r!==E){d=r;k=0;for(y=d.keyFrames.length;k<y;k++){q=d.keyFrames[k];for(f={};null!==(w=Ia.exec(q.props));)c=
w[1],e=w[2],w=c.match(Ja),null!==w?(c=w[1],w=w[2]):w="linear",e=e.indexOf("!")?Ma(e):[e.slice(1)],f[c]={value:e,easing:M[w]};q.props=f}d={};y=k=void 0;k=0;for(y=r.keyFrames.length;k<y;k++)wa(r.keyFrames[k],d);d={};for(k=r.keyFrames.length-1;0<=k;k--)wa(r.keyFrames[k],d)}return n};u.prototype.relativeToAbsolute=function(a,b,h){var r=c.clientHeight,d=a.getBoundingClientRect();a=d.top;d=d.bottom-d.top;"bottom"===b?a-=r:"center"===b&&(a-=r/2);"bottom"===h?a+=d:"center"===h&&(a+=d/2);a+=n.getScrollTop();
return a+.5|0};u.prototype.animateTo=function(a,b){b=b||{};var h=J(),r=n.getScrollTop();l={startTop:r,topDiff:a-r,targetTop:a,duration:b.duration||1E3,startTime:h,endTime:h+(b.duration||1E3),easing:M[b.easing||"linear"],done:b.done};l.topDiff||(l.done&&l.done.call(n,!1),l=E);return n};u.prototype.stopAnimateTo=function(){l&&l.done&&l.done.call(n,!0);l=E};u.prototype.isAnimatingTo=function(){return!!l};u.prototype.setScrollTop=function(a,b){!0===b&&(I=a,Q=!0);B?O=f.min(f.max(a,0),x):g.scrollTo(0,a);
return n};u.prototype.getScrollTop=function(){return B?O:g.pageYOffset||c.scrollTop||v.scrollTop||0};u.prototype.on=function(a,b){F[a]=b;return n};u.prototype.off=function(a){delete F[a];return n};var Ba=function(){var a,b,h,r,d,k,y,q,l,m;ia(c,"touchstart touchmove touchcancel touchend",function(c){c.preventDefault();var e=c.changedTouches[0];r=e.clientY;d=e.clientX;q=c.timeStamp;switch(c.type){case "touchstart":a&&a.blur();n.stopAnimateTo();a=c.target;b=k=r;h=d;break;case "touchmove":y=r-k;m=q-l;
n.setScrollTop(O-y,!0);k=r;l=q;break;default:case "touchcancel":case "touchend":c=b-r;e=h-d;if(49>e*e+c*c){a.focus();a.click();break}a=E;e=y/m;e=f.max(f.min(e,3),-3);c=f.abs(e/W);var e=e*c+.5*W*c*c,g=n.getScrollTop()-e,p=0;g>x?(p=(x-g)/e,g=x):0>g&&(p=-g/e,g=0);n.animateTo(g,{easing:"outCubic",duration:c*(1-p)})}});g.scrollTo(0,0);c.style.overflow=v.style.overflow="hidden"},Ma=function(a){var b=[];sa.lastIndex=0;a=a.replace(sa,function(a){return a.replace(qa,function(a){return a/255*100+"%"})});C&&
(ta.lastIndex=0,a=a.replace(ta,function(a){return C+a}));a=a.replace(qa,function(a){b.push(+a);return"{?}"});b.unshift(a);return b},wa=function(a,b){for(var h in b)ba.call(a.props,h)||(a.props[h]=b[h]);for(h in a.props)b[h]=a.props[h]},oa=function(a){var b=1;ra.lastIndex=0;return a[0].replace(ra,function(){return a[b++]})},aa=function(a,b){a=[].concat(a);for(var h,c,d=0,k=a.length;d<k;d++)if(c=a[d],h=z[c.___skrollable_id])b?(c.style.cssText=h.dirtyStyleAttr,H(c,h.dirtyClassAttr)):(h.dirtyStyleAttr=
c.style.cssText,h.dirtyClassAttr=va(c),c.style.cssText=h.styleAttr,H(c,h.classAttr))},Aa=function(){P="translateZ(0)";K.setStyle(G,"transform",P);var a=ca(G),b=a.getPropertyValue("transform"),a=a.getPropertyValue(C+"transform");b&&"none"!==b||a&&"none"!==a||(P="")};K.setStyle=function(a,b,c){a=a.style;b=b.replace(Ka,La).replace("-","");if("zIndex"===b)a[b]=""+(c|0);else if("float"===b)a.styleFloat=a.cssFloat=c;else try{m&&(a[m+b.slice(0,1).toUpperCase()+b.slice(1)]=c),a[b]=c}catch(g){}};var ia=K.addEvent=
function(a,b,c){var f=function(a){a=a||g.event;a.target||(a.target=a.srcElement);a.preventDefault||(a.preventDefault=function(){a.returnValue=!1});return c.call(this,a)};b=b.split(" ");for(var d=0,k=b.length;d<k;d++)a.addEventListener?a.addEventListener(b[d],c,!1):a.attachEvent("on"+b[d],f)},la=function(){var a=n.getScrollTop();x=0;N&&!B&&(v.style.height="auto");var b,h,g,d,k,l,q,m,u;m=0;for(u=z.length;m<u;m++)for(b=z[m],h=b.element,g=b.anchorTarget,d=b.keyFrames,k=0,l=d.length;k<l;k++)q=d[k],"relative"===
q.mode&&(aa(h),q.frame=n.relativeToAbsolute(g,q.anchors[0],q.anchors[1])-q.offset,aa(h,!0)),N&&!q.isEnd&&q.frame>x&&(x=q.frame);x=f.max(x,f.max(G&&G.offsetHeight||0,v.scrollHeight,v.offsetHeight,c.scrollHeight,c.offsetHeight,c.clientHeight)-c.clientHeight);m=0;for(u=z.length;m<u;m++){b=z[m];d=b.keyFrames;k=0;for(l=d.length;k<l;k++)q=d[k],q.isEnd&&(q.frame=x-q.offset);b.keyFrames.sort(Na)}N&&!B&&(v.style.height=x+c.clientHeight+"px");B?n.setScrollTop(f.min(n.getScrollTop(),x)):n.setScrollTop(a,!0);
Q=!0},va=function(a){var b="className";g.SVGElement&&a instanceof g.SVGElement&&(a=a[b],b="baseVal");return a[b]},H=function(a,b,c){var f="className";g.SVGElement&&a instanceof g.SVGElement&&(a=a[f],f="baseVal");if(c===E)a[f]=b;else{for(var d=a[f],k=0,l=c.length;k<l;k++)d=(" "+d+" ").replace(" "+c[k]+" "," ");d=d.replace(pa,"");c=0;for(k=b.length;c<k;c++)-1===(" "+d+" ").indexOf(" "+b[c]+" ")&&(d+=" "+b[c]);a[f]=d.replace(pa,"")}},J=Date.now||function(){return+new Date},Na=function(a,b){return a.frame-
b.frame},n,z,G,F,N,x=0,fa=1,da,W,ma="down",I=-1,Z=J(),ka=0,ja=0,Y=!1,l,ga,X,Q,ua=0,ea,B=!1,O=0,P})(window,document);